src/main/java/boundary/controllers/UserController.java
package boundary.controllers;

import domain.Tweet;
import domain.User;
import services.TweetService;
import services.UserService;
import util.enums.UserType;

import javax.enterprise.context.RequestScoped;
import javax.faces.context.FacesContext;
import javax.inject.Inject;
import javax.inject.Named;
import java.util.Collection;
import java.util.Map;

@Named
@RequestScoped
public class UserController {

    private long userId;
    private String name;
    private String type;
    private String bio;
    private String location;
    private String website;
    private User selectedUser;

    //<editor-fold defaultstate="collapsed" desc="getters and setters">
    public long getUserId() {
        return userId;
    }

    public void setUserId(long userId) {
        this.userId = userId;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getBio() {
        return bio;
    }

    public void setBio(String bio) {
        this.bio = bio;
    }

    public String getLocation() {
        return location;
    }

    public void setLocation(String location) {
        this.location = location;
    }

    public String getWebsite() {
        return website;
    }

    public void setWebsite(String website) {
        this.website = website;
    }

    public User getSelectedUser() {
        return selectedUser;
    }

    public void setSelectedUser(User selectedUser) {
        this.selectedUser = selectedUser;
    }

    //</editor-fold>

    @Inject
    private TweetService tweetService;

    @Inject
    private UserService userService;

    /**
     * gets all users from the database
     * @return Response
     */
    public Collection<User> getAllUsers(){
        Collection<User> userlist = userService.findAllUsers();
        for (User u : userlist){
            if(u.getType() == UserType.ADMIN){
                userlist.remove(u);
                break;
            }
        }
        return userlist;
    }

    /**
     * deletes a user from database
     */
    public void delete(){
        userService.removeUser(this.selectedUser);
    }

    /**
     * retrieves data from user and sets it to selectedUser object
     */
    public void retrieveUser(){
        User tmp = userService.findUser(userId);
        this.setvariables(tmp);
    }

    /**
     * edits a user object
     * @return String
     */
    public String editUser(){
        userService.editUser(this.updateUser());
        return "useroverview?faces-redirect=true";
    }

    /**
     * sets all the controller fields
     * @param user
     */
    private void setvariables(User user){
        this.name = user.getName();
        this.type = user.getType().toString();
        this.bio= user.getBio();
        this.location = user.getLocation();
        this.website = user.getWebsite();
    }

    /**
     * retrieve user object and change values
     * @return User
     */
    private User updateUser(){
        FacesContext fc = FacesContext.getCurrentInstance();
        Map<String,String> params =
                fc.getExternalContext().getRequestParameterMap();

        User tmp = userService.findByName(params.get("username"));
        tmp.setType(UserType.valueOf(this.type));
        tmp.setBio(this.bio);
        tmp.setLocation(this.location);
        tmp.setWebsite(this.website);
        return tmp;
    }
}

src/main/webapp/views/edituser.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">
<h:head>
    <title>overview</title>

    <f:metadata>
        <f:viewParam name="userId" value="#{userController.userId}" />
        <f:event type="preRenderView" listener="#{userController.retrieveUser()}"/>
    </f:metadata>
</h:head>
<h:body>
    <ui:composition template="template/layout.xhtml">
        <ui:define name="content">
            <f:view>
                <h:form>
                    <h:panelGrid columns="3" cellpadding="5">
                        <p:outputLabel value="Name:" for="name"/>
                        <p:inputText id="name" value="#{userController.name}" readonly="true"/>
                        <p:message for="name" />

                        <p:outputLabel value="Type:" for="type" />
                        <p:selectOneMenu id="type" value="#{userController.type}" style="width:125px" required="true">
                            <f:selectItem itemLabel="NORMAL" itemValue="NORMAL" />
                            <f:selectItem itemLabel="MODERATOR" itemValue="MODERATOR" />
                        </p:selectOneMenu>
                        <p:message for="type" />

                        <p:outputLabel value="Biography" for="bio" />
                        <p:inputTextarea id="bio" rows="10" cols="50" value="#{userController.bio}" required="true"/>
                        <p:message for="bio" />

                        <p:outputLabel value="Location" for="location" />
                        <p:inputText id="location" value="#{userController.location}" required="true"/>
                        <p:message for="location" />

                        <p:outputLabel value="Website" for="web"/>
                        <p:inputText id="web" value="#{userController.website}" required="true"/>
                        <p:message for="web" />
                    </h:panelGrid>
                    <p:commandButton value="Submit" action="#{userController.editUser()}">
                        <f:param name="username" value="#{userController.name}" />
                    </p:commandButton>
                </h:form>
            </f:view>
        </ui:define>
    </ui:composition>
</h:body>
</html>

src/main/webapp/views/tweetoverview.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">
<h:head>
    <title>overview</title>

    <f:metadata>
        <f:viewParam name="userId" value="#{tweetController.userId}" />
        <f:event type="preRenderView" listener="#{tweetController.retrieveTweets}"/>
    </f:metadata>
</h:head>
<h:body>
    <ui:composition template="template/layout.xhtml">
        <ui:define name="content">
            <f:view>
                <h:form id="tweetForm">
                    <p:dataTable id="tweetTable" var="tweet" value="#{tweetController.tweets}" tableStyle="table-layout:auto;width:100%;">
                        <f:facet name="header">
                            Tweets
                        </f:facet>
                        <p:column headerText="Text">
                            <h:outputText value="#{tweet.tweet}" />
                        </p:column>

                        <p:column headerText="Sender">
                            <h:outputText value="#{tweet.sender.name}" />
                        </p:column>

                        <p:column headerText="Posted At">
                            <h:outputText value="#{tweet.postedAt}">
                                <f:convertDateTime pattern="dd.MM.yyyy HH:mm" />
                            </h:outputText>
                        </p:column>

                        <p:column headerText="Likes">
                            <h:outputText value="#{tweet.likes.size()}" />
                        </p:column>

                        <p:column style="width:32px; text-align: center">
                            <p:commandButton value="Remove" icon="ui-icon-trash"
                                             action="#{tweetController.delete}"
                                             update=":tweetForm:tweetTable"
                                             ajax="true">
                                <f:setPropertyActionListener target="#{tweetController.selectedTweet}" value="#{tweet}" />
                                <f:param name="userId" value="#{tweetController.userId}" />
                            </p:commandButton>
                        </p:column>
                    </p:dataTable>
                </h:form>
            </f:view>
        </ui:define>
    </ui:composition>
</h:body>
</html>

src/main/webapp/views/useroverview.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">
<h:head>
    <title>overview</title>
</h:head>
<h:body>
    <ui:composition template="template/layout.xhtml">
        <ui:define name="content">
            <f:view>
                <h:form id="userForm">
                    <p:dataTable id="userTable" var="user" value="#{userController.allUsers}" tableStyle="table-layout:auto;width:100%;">
                        <f:facet name="header">
                            Users
                        </f:facet>
                        <p:column headerText="Id">
                            <h:outputText value="#{user.id}" />
                        </p:column>

                        <p:column headerText="Name">
                            <h:outputText value="#{user.name}" />
                        </p:column>

                        <p:column headerText="Type">
                            <h:outputText value="#{user.type}" />
                        </p:column>

                        <p:column headerText="Biography">
                            <h:outputText value="#{user.bio}" />
                        </p:column>

                        <p:column headerText="Website">
                            <h:outputText value="#{user.website}" />
                        </p:column>

                        <p:column headerText="Action" style="width:32px; text-align: center">
                            <h:button value="Tweets" icon="ui-icon-search" outcome="tweetoverview">
                                <f:param name="userId" value="#{user.id}" />
                            </h:button>
                            <h:button value="Edit" outcome="edituser">
                                <f:param name="userId" value="#{user.id}" />
                            </h:button>
                            <p:commandButton value="Remove" icon="ui-icon-trash"
                                             action="#{userController.delete}"
                                             update=":userForm:userTable"
                                             ajax="true">
                                <f:setPropertyActionListener
                                        target = "#{userController.selectedUser}" value = "#{user}" />
                            </p:commandButton>
                        </p:column>
                    </p:dataTable>
                </h:form>
            </f:view>
        </ui:define>
    </ui:composition>
</h:body>
</html>